name: 'my-github-review'
description: 'my first try github action'
author: 'Jaja'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  token:
    description: 'Your GITHUB TOKEN'
    default: ${{ github.token }}
    required: false
  openaikey:
    description: 'Your OPENAPI KEY'
    default: ${{ github.openaikey }}
    required: false
  prompt:
    description: 'Your prompt of codereview'
    default: ${{ github.prompt }}
    required: false
  commentLng:
    description: 'Your code review result of comment language'
    default: ${{ github.commentLng }}
    required: false  
# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
